### ISSUE TITLE
흰디카 도메인 API 개발

### ISSUE THREAD

**Issue by deingvelop** [bogle-bogle/thepet-backend#12]
## Feature Description
- 흰디카 1차 백엔드 개발

## Todo list
- [ ] 흰디카 예약하기 (30분 후 자동 취소 로직도 필요)
- [ ] 흰디카 예약 픽업 완료
- [x] 흰디카 잔여개수 조회하기

**Comment by deingvelop** [comment]
## 예약 취소 구현 방법 고민

### 1. Trigger
```sql
CREATE OR REPLACE TRIGGER reservation_auto_cancel
AFTER INSERT ON reservation
FOR EACH ROW
DECLARE
    v_completed_yn reservation.completed_yn%TYPE;
BEGIN
    -- 예약이 삽입될 때마다 해당 예약의 COMPLETED_YN 값을 읽어옴
    SELECT completed_yn INTO v_completed_yn
    FROM reservation
    WHERE reservation_id = :new.reservation_id;

    -- 일정 시간 내에 COMPLETED_YN 값이 변경되지 않으면 예약을 취소
    -- 여기서는 30분으로 가정
    DBMS_LOCK.sleep(1800); -- 30분을 초 단위로 변환

    SELECT completed_yn INTO v_completed_yn
    FROM reservation
    WHERE reservation_id = :new.reservation_id;

    IF v_completed_yn = 'N' THEN
        UPDATE reservation
        SET status = 'CANCELLED'
        WHERE reservation_id = :new.reservation_id;
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        -- 처리할 내용 없음
    WHEN OTHERS THEN
        -- 에러 처리
        NULL;
END;
/
```
장점:
- 데이터 일관성 유지: 트리거를 사용하면 데이터 일관성을 유지하면서 원하는 동작을 수행할 수 있습니다.
- 데이터베이스 내부에서 처리: 트리거를 사용하면 데이터베이스 내부에서 작업을 처리할 수 있어 데이터 일관성과 안전성을 유지하기 쉽습니다.

단점 및 고려사항:
- 성능 이슈: 트리거는 데이터베이스 작업을 트리거링하므로 성능 이슈가 발생할 수 있습니다. 특히 대량의 작업이나 동시성이 높은 환경에서는 성능 저하 문제가 발생할 수 있습니다.
- 복잡성과 유지보수: 복잡한 트리거를 만들 경우 코드를 이해하고 유지보수하기가 어려울 수 있습니다.
- 데드락 위험: 트리거에서 잠금을 설정하거나 여러 작업을 수행할 경우 데드락과 같은 문제가 발생할 수 있습니다.

### 2. Trigger를 통해 Oracle Job Scheduler를 생성하기
```sql
BEGIN
  DBMS_SCHEDULER.create_job (
    job_name        => 'AUTO_CANCEL_JOB',
    job_type        => 'PLSQL_BLOCK',
    job_action      => 'BEGIN YOUR_AUTO_CANCEL_PROCEDURE; END;',
    start_date      => SYSTIMESTAMP,
    repeat_interval => 'FREQ=HOURLY; INTERVAL=1', -- 1시간마다
    enabled         => TRUE
  );
END;
/
```

장점:
- 데이터베이스 내부 처리: PL/SQL은 데이터베이스 내에서 실행되므로 데이터 일관성과 안전성을 보다 쉽게 유지할 수 있습니다.
- 데이터베이스 기능 활용: 데이터베이스 내장 함수와 프로시저를 활용하여 복잡한 작업을 수행할 수 있습니다.
- 트리거 및 스케줄러 활용: 트리거와 스케줄러를 통해 데이터 변경 및 일정 시간 후 작업을 자동으로 처리할 수 있습니다.

단점:
- 유연성 제한: 데이터베이스 내에서 처리되므로 데이터베이스 외부 서비스와의 통합이 어려울 수 있습니다.
- 트랜잭션과 롤백: 트랜잭션 관리와 롤백이 상대적으로 제한적일 수 있습니다.
- 복잡성 증가: 복잡한 비즈니스 로직을 처리하기에는 Java 코드보다 제한적일 수 있습니다.

### 3. Java에서 Timer 등의 클래스를 활용하여 비즈니스 로직 작성
```sql
ScheduledExecutorService executor = Executors.newSingleThreadScheduledExecutor();
        executor.schedule(() -> System.out.println("여기서 자동 삭제 실행 예정"), 30, TimeUnit.MINUTES);
        executor.shutdown();
```
장점:
- 유연성과 제어: Java 코드를 사용하면 개발자가 작업을 더 세밀하게 제어하고 구현할 수 있습니다. 복잡한 비즈니스 로직이나 다양한 조건 처리가 필요한 경우에 유용합니다.
- 외부 서비스 통합: Java는 다양한 라이브러리와 프레임워크를 활용하여 외부 서비스와의 통합이 용이합니다. 웹 서비스 호출, 메시징 시스템 연동 등을 쉽게 구현할 수 있습니다.

단점:
- 트랜잭션 관리와 일관성: Java에서 트랜잭션 관리를 세밀하게 해야 하며, 데이터베이스와의 일관성을 유지하기 위해 노력이 필요합니다.
- 응답성: Java 코드를 실행하는 데는 시간이 소요될 수 있으므로, 실시간 반응성이 중요한 경우에는 주의가 필요합니다.

**Comment by deingvelop** [comment]
### 의사결정
- 예약할 때 잔여 흰디카 개수도 -1되는 로직 : spring단에서 같은 transaction
- 30분후까지 픽업되지 않으면 자동 취소되는 로직 : Spring에서 Java Timer 이용
- 예약이 자동 취소되면 잔여 예약수 갱신되는 로직 : Trigger
- 흰디카가 반납되면 잔여 예약수 갱신되는 로직 : Trigger

**Comment by deingvelop** [comment]
## 성능 개선
INDEX 붙일 COLUMN

- CM_CODE의 CODE_VALUE
- CM_CODE의 PARENT_CODE
- CM_CODE의 SECT_CODE
- BRANCH_HEENDY_CAR의 BRANCH_CODE
