### ISSUE TITLE
2차 오류 수정

### ISSUE THREAD

**Issue by deingvelop** [bogle-bogle/thepet-backend#141]
## Feature Description
- 장바구니
- ADMIN
- 구독 (Subscription)
- 흰디카
- global
- 마이페이지

## Todo list
- 장바구니
  - [x] 장바구니 삭제 로직
  - [x] 장바구니 → 선택한 상품만 주문
- 구독 (Subscription)
  - [x] 구독 → 로직 수정(curation 예외처리)
  - [ ] 구독 정기 처리
  - [x] 구독 - 프론트 연결
- 흰디카
  - [x] 흰디카 예약과 event 분리
  - [x] 전화번호 없어서 예약 안되면 -> 오류 메시지 커스텀화
  - [x] 흰디카 - 이미 오늘 예약이 있으면 또 안 되게 하기
  - [x] 마이페이지 -> 예약 취소 기능
  - [ ] 예약이 취소되면서 문자 또 가게 하기
- global
  - [x] 레디스 없어서 안되면 -> 오류 메시지 커스텀화

### 2.5차 수정
- 강아지 등록
  - [ ] 강아지 사진 등록 + addpet 동시에 -> 리팩토링
- 커스텀 카드 저장 및 마이페이지에서 조회
