### ISSUE TITLE
3차 오류 수정

### ISSUE THREAD

**Issue by deingvelop** [bogle-bogle/thepet-backend#161]
## Todo list
- [ ]  구독 정기 처리
- [ ] 예약이 취소되면서 문자 또 가게 하기
- [ ] 강아지 사진 등록 + addpet 동시에 -> 리팩토링
- [ ] 커스텀 카드 저장 및 마이페이지에서 조회
