### ISSUE TITLE
4차 오류 수정

### ISSUE THREAD

**Issue by deingvelop** [bogle-bogle/thepet-backend#181]
## Feature Description
- 

## Todo list
- [ ]  구독 정기 처리
- [x] 예약이 취소되면서 문자 또 가게 하기
- [ ] 강아지 사진 등록 + addpet 동시에 -> 리팩토링
- [x] Kafka로 로깅 변경
- [x] 강아지 사료 등록 -> Spring에서 하도록 변경
