### ISSUE TITLE
원짱 테이블 PK값들 -> 특성을 나타내는 VARCHAR 값으로 바꾸기

### ISSUE THREAD

**Issue by deingvelop** [bogle-bogle/thepet-backend#68]
## Feature Description
- 

## Todo list
- [ ] MEMBER 테이블 값 - ex) `C00000001` (Customer) or  `M00000001` (Mustomer)
- [ ] ORDER 테이블 값 - ex) `O00000001` 
- [ ] PRODUCT 테이블값  - ex) `PFD41000001`
- [ ] 기타
