### ISSUE TITLE
테이블 PK -> 특성을 나타내는 VARCHAR 값으로 바꾸기

### ISSUE THREAD

**Issue by deingvelop** [bogle-bogle/thepet-backend#71]
## Todo list
- [ ] MEMBER 테이블 값 - ex) `C00000001` (Customer) or  `M00000001` (Mustomer)
- [ ] ORDER 테이블 값 - ex) `O00000001` 
- [ ] PRODUCT 테이블값  - ex) `PRDFD41000001`
- [ ] PET 테이블값 - ex) `P00000001`
- [ ] 기타
